### ISSUE TITLE
Standalone client.py and server.py + pip package

### ISSUE THREAD

**Issue by maaaaz** [klsecservices/rpivot#1]
Hello @artkond,

First let me greet you for this cool tool you developed !

Then, I have few improvement ideas to share:
* Have single standalone `client.py` and `server.py` files: today they both depend on `relay.py`. Having just to download a single file on each side (either client or server) would be awesome
* Have a pip package: it would be even more awesome if we could just `pip install rpivot` after gaining access on a target. I can help on that point if you are interested

Cheers !

**Comment by artkond** [comment]
Partially solved by launching from zip in #3
